[colors.bright]
black = "#949494"
blue = "#74b2ff"
cyan = "#85dc85"
green = "#36c692"
magenta = "#ae81ff"
red = "#ff5189"
white = "#e4e4e4"
yellow = "#bfbf97"

[colors.cursor]
cursor = "#b2b2b2"
text = "#080808"

[colors.normal]
black = "#323437"
blue = "#80a0ff"
cyan = "#79dac8"
green = "#8cc85f"
magenta = "#d183e8"
red = "#ff5454"
white = "#c6c6c6"
yellow = "#e3c78a"

[colors.primary]
background = "#080808"
foreground = "#b2b2b2"

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Never"

[env]
TERM = "xterm-256color"

[font]
size = 18

[font.glyph_offset]
y = 9

[font.normal]
family = "SFMono Nerd Font"

[font.offset]
y = 16

[scrolling]
history = 2000

[window]
decorations = "buttonless"
opacity = 0.98

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 5
y = 5
